pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        GITHUB_CREDENTIALS = 'a1c4e262-6cc1-4313-9f81-16863ac71a13' // The ID of the credentials in Jenkins
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    // Use the credentials to clone the repo
                    git credentialsId: GITHUB_CREDENTIALS, url: 'https://github.com/Tharanga49/simple-java-maven-app'
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
               sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
