pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2' // Ensure the volume path is correct based on your OS
            --entrypoint /bin/bash
            -c "apt-get update && apt-get install -y git && bash"
        }
    }
    tools {
        git 'Tharanga49'  // Use the Git installation named 'Tharanga49'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm  // This will checkout the code using the configured Git tool
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
